### PR TITLE
Account for GMT offset

### PR DESCRIPTION
**Pull request by theukedge**
As it stands, plugin does not account for GMT offset if the YOURLS_HOURS_OFFSET constant is defined. This fixes that.

### CODE REVIEW

**Comment by vaughany** [comment]
Hey. I like the PR but it seems that it's going to overwrite a change in my branch that you don't have in your fork, specifically [this commit](https://github.com/vaughany/yourls-popular-clicks-extended/commit/fbc0a8e94e7301790de6422cc4c946c448cf41fe).  Could you pull from the master branch or cherry-pick that commit?

Cheers.

**Comment by theukedge** [comment]
Are you sure? It looks as though those lines are [included in my master](https://github.com/theukedge/yourls-popular-clicks-extended/blob/master/plugin.php#L179-L190)?

**Comment by vaughany** [comment]
So they are. Odd. Not sure what I was looking at then!

**Comment by theukedge** [comment]
Not a problem. Thanks for the merge :)

**Pull request merged**
